# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'WuxusTask' do
pod 'Alamofire'
pod 'SwiftyJSON' , :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'AFMInfoBanner'
end

target 'WuxusTaskTests' do

end

target 'WuxusTaskUITests' do

end

